tests: Fix build on x86_32
The build of measure_wakeup_latency and measure_latency test fails due to
missing rdtsc's support for x86_32.
This adds support rdtsc for x86_32.

Build log: https://buildd.debian.org/status/fetch.php?pkg=massivethreads&arch=i386&ver=1.00-1&stamp=1613918118&raw=0
```
measure_latency.c: In function ‘f’:
measure_latency.c:17:3: error: inconsistent operand constraints in an‘asm’
   17 |   asm volatile ("rdtsc;shlq $32,%%rdx;orq %%rdx,%%rax":"=a"(u)::"%rdx");
      |   ^~~
```

Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@debian.org>